<a href="https://colab.research.google.com/github/khusanovich/colab-jupyter_notebook/blob/main/2_1_3_logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash
### Mantiqiy shart operatorlarni massiv operator sifatida qo'llash
### Shart operatori sifatida `where` dan foydalanish
### Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: `xarr` va `yarr`. Agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [2]:
arr0 = np.array([0, 2, 4, 6])
arr1 = np.array([1, 3, 5, 7])

In [3]:
# shart
cond = np.array([True, True, False, False])

In [5]:
# where
result = np.where(cond, arr0, arr1)

In [6]:
result

array([0, 2, 5, 7])

In [10]:
arr3 = np.random.randint(10, size=(4, 4))

In [12]:
arr3

array([[1, 8, 2, 3],
       [0, 9, 8, 1],
       [4, 0, 3, 4],
       [0, 7, 7, 9]])

In [19]:
results = np.where(arr3<4, 0, 1) # element 4 dan kichik bo'lsa 0 ni chiqar, aks holda 1 ni


In [20]:
results

array([[0, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 1]])

In [21]:
results0 = np.where(arr3<9, 0, 1) # element 9 dan kichik bo'lsa 0 ni chiqar, aks holda 1 ni

In [22]:
results0

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]])