<a href="https://colab.research.google.com/github/khusanovich/colab-jupyter_notebook/blob/main/2_1_3_sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5) # rand metodi 0 va 1 oralig'idagi sonlardan iborat taxminiy array(massiv) yaratadi

In [3]:
arr

array([0.75643318, 0.82723886, 0.65929704, 0.13357788, 0.81188388])

### `sort` funkiyasi

In [5]:
# 1- usul
sorted_arr = np.sort(arr) #  arr massivini tartiblangan ko'rinishini sorted_arr joylaydi
sorted_arr

array([0.13357788, 0.65929704, 0.75643318, 0.81188388, 0.82723886])

In [6]:
# 2- usul
arr.sort()


In [7]:
arr

array([0.13357788, 0.65929704, 0.75643318, 0.81188388, 0.82723886])

In [10]:
# teskari tartiblash
rev_arr = -np.sort(-arr)
rev_arr

array([0.82723886, 0.81188388, 0.75643318, 0.65929704, 0.13357788])

In [25]:
# 2d array
arr2d = np.random.randint(10, size=(4, 5))
arr2d

array([[4, 6, 1, 3, 2],
       [4, 7, 5, 8, 6],
       [2, 3, 8, 0, 0],
       [7, 5, 7, 1, 0]])

In [26]:
arr2d.ndim

2

In [27]:
row_sort = np.sort(arr2d, axis=1) # qator tartiblaydi
row_sort

array([[1, 2, 3, 4, 6],
       [4, 5, 6, 7, 8],
       [0, 0, 2, 3, 8],
       [0, 1, 5, 7, 7]])

In [28]:
col_sort = np.sort(arr2d, axis=0) # ustunni tartiblaydi
col_sort

array([[2, 3, 1, 0, 0],
       [4, 5, 5, 1, 0],
       [4, 6, 7, 3, 2],
       [7, 7, 8, 8, 6]])