<a href="https://colab.research.google.com/github/khusanovich/colab-jupyter_notebook/blob/main/2_1_3_math%26statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.random.randn(4, 5)
arr

array([[ 1.28497948, -0.1709312 , -0.53160137,  1.48367992, -0.33974305],
       [ 0.22961797,  1.02086398, -0.32577292,  1.50112543,  0.57448881],
       [-0.91740088, -0.24024791, -0.35828232,  0.0341655 , -0.935298  ],
       [-0.04435323,  0.52158242, -0.79110991, -0.19085096, -0.68762061]])

### `sum` metodi

In [5]:
arr.sum() # arr ning barcha elementlarni yig'indisini hisoblab beradi

1.1172911516624486

In [7]:
# sum ning boshqacha usuli
np.sum(arr)

1.1172911516624486

In [8]:
arr.sum(axis=0) # ustun yi'gindi

array([ 0.55284334,  1.13126729, -2.00676653,  2.8281199 , -1.38817285])

In [10]:
arr.sum(axis=1) # qator yig'indisi

array([ 1.72638379,  3.00032327, -2.41706361, -1.1923523 ])

### `mean` metodi

In [13]:
# mean o'rta arifmetikni hisoblaydi
data = np.arange(4)

In [14]:
data

array([0, 1, 2, 3])

In [15]:
# o'rta arifmetik uchun oddiy misol
mean = data.sum()/len(data)
mean

1.5

In [16]:
data.mean() # numpy mean

1.5

In [17]:
np.mean(data) #numpy mean

1.5

In [18]:
arr

array([[ 1.28497948, -0.1709312 , -0.53160137,  1.48367992, -0.33974305],
       [ 0.22961797,  1.02086398, -0.32577292,  1.50112543,  0.57448881],
       [-0.91740088, -0.24024791, -0.35828232,  0.0341655 , -0.935298  ],
       [-0.04435323,  0.52158242, -0.79110991, -0.19085096, -0.68762061]])

In [19]:
np.mean(arr) # arr arriyining o'rta arifmetigi

0.055864557583122434

In [20]:
np.mean(arr, axis=0) # ustun bo'yicha o'rta arifmetik

array([ 0.13821084,  0.28281682, -0.50169163,  0.70702998, -0.34704321])

In [21]:
np.mean(arr, axis=1) # har bir qator o'rta arifmetigi

array([ 0.34527676,  0.60006465, -0.48341272, -0.23847046])

### `cumsum` metodi

In [22]:
data

array([0, 1, 2, 3])

In [24]:
data.cumsum() # o'zigacha bo'lgan sonlarni qo'shib shu joyga yozadi(o'zi ham kiradi)

array([0, 1, 3, 6])