<a href="https://colab.research.google.com/github/khusanovich/colab-jupyter_notebook/blob/main/2_1_3_files_save_z.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr0 = np.arange(10)
arr0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('data0', arr0)

In [6]:
arr1 = np.load('data0.npy')

In [7]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1 = np.arange(20)

In [9]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
np.savez('arrays', a = arr0, b = arr1)

In [11]:
arrays0 = np.load('arrays.npz')

In [15]:
arrays0['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arrays0['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
np.savez_compressed('array_comp.npz', a=arr0, b=arr1)