<a href="https://colab.research.google.com/github/khusanovich/colab-jupyter_notebook/blob/main/2_1_2_universal_funktions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

2.1.2. Universal funksiyalar

Unary funksiyalar (bitta argument qabul qiluvchi funkisya)

sqrt, square, exp, log, modf, sign, isnan funksiyalarini ko'rib chiqamiz

In [4]:
arr0 = np.arange(10) # 0 ~ 10 gacha bo'lgan elementlardan iborat massivni qaytaradi

In [5]:
arr0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `sqrt` massivning xar bir elementini kvadrat ildizni qaytaradi


In [6]:
np.sqrt(arr0)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

### `square` massivning xar bir elementini kvadratga oshiradi


In [7]:
np.square(arr0)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### `exp` massivning xar bir elementini eksponentini qaytaradi

In [8]:
np.exp(arr0)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

### `log` massivning xar bir logorifmini hisoblaydi

In [13]:
np.log(arr0[1:])  # arr nomli massivning 0-elementdan tashqari barcha elementlarini logarifmini hisoblaydi (loge)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

### `modf` bu funksiya haqiqiy sonlarni butun va qoldiq qismlarini ajratib beruvchi funksiya

In [16]:
arr1 = np.random.randn(10)
arr1

array([-0.01030888,  1.09942122, -1.4938024 ,  0.43725935, -0.59118174,
        0.89115578, -1.54523177,  0.60991792,  1.41926675,  0.73656344])

In [17]:
butun, qoldiq = np.modf(arr1) # arr1 ning elementlarini qoldiq va butun qismlarini ikkita massivga ajratadi

In [18]:
print(butun)
print(qoldiq)

[-0.01030888  0.09942122 -0.4938024   0.43725935 -0.59118174  0.89115578
 -0.54523177  0.60991792  0.41926675  0.73656344]
[-0.  1. -1.  0. -0.  0. -1.  0.  1.  0.]


### `sign` funkisyasi massiv elementlarini qiymati manfiy bo'lsa `-1` va aksincha musbat bo'lsa `1` ni qaytaradi

In [20]:
np.sign(arr1)

array([-1.,  1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1.])

### `isnan` massivning elementlarida NaN ma'lumoti bo'lsa `True` qaytaradi va aksincha esa `False` qaytaradi

In [21]:
arr1

array([-0.01030888,  1.09942122, -1.4938024 ,  0.43725935, -0.59118174,
        0.89115578, -1.54523177,  0.60991792,  1.41926675,  0.73656344])

In [22]:
np.isnan(arr1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [23]:
arr1[0] = np.NaN # 0- elementimizni nan ga almashtirish

In [24]:
np.isnan(arr1)

array([ True, False, False, False, False, False, False, False, False,
       False])

In [25]:
arr1

array([        nan,  1.09942122, -1.4938024 ,  0.43725935, -0.59118174,
        0.89115578, -1.54523177,  0.60991792,  1.41926675,  0.73656344])

### Binary funksiyalar (ikkita argument qabul qiluvchi funkisya)
### `add`, `multiply`, `maximum` funksiyalarini ko'rib chiqamiz
### `add` ikkita massivning mos elementlarini qo'shadi

In [29]:
arr2 = np.random.randn(10)
arr3 = np.random.randn(10)

In [30]:
arr2

array([-0.6329525 ,  0.67408918, -0.95126054, -0.13404851,  0.12283256,
        1.27371848,  0.98244466,  0.4212677 ,  0.80167511,  1.97253313])

In [31]:
arr3

array([ 0.24778223, -0.45379952, -0.4683328 ,  0.58986736,  0.87397543,
        0.88844783, -0.20518309, -0.57193515,  2.2625502 ,  0.84599227])

In [33]:
np.add(arr2, arr3) # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi

array([-0.38517027,  0.22028967, -1.41959334,  0.45581885,  0.99680799,
        2.1621663 ,  0.77726157, -0.15066745,  3.06422531,  2.8185254 ])

In [34]:
arr2 + arr3 # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi


array([-0.38517027,  0.22028967, -1.41959334,  0.45581885,  0.99680799,
        2.1621663 ,  0.77726157, -0.15066745,  3.06422531,  2.8185254 ])

### `multiply` ikkita massivning mos elementlarini ko'paytiradi

In [35]:
np.multiply(arr2, arr3)

array([-0.15683438, -0.30590134,  0.44550651, -0.07907084,  0.10735264,
        1.13163241, -0.20158103, -0.24093781,  1.81383018,  1.66874778])

### `maximum` ikkita massivning elementlarin taqqoslab ulardan kattasining qiymatini qaytaradi

In [38]:
arr2

array([-0.6329525 ,  0.67408918, -0.95126054, -0.13404851,  0.12283256,
        1.27371848,  0.98244466,  0.4212677 ,  0.80167511,  1.97253313])

In [39]:
arr3

array([ 0.24778223, -0.45379952, -0.4683328 ,  0.58986736,  0.87397543,
        0.88844783, -0.20518309, -0.57193515,  2.2625502 ,  0.84599227])

In [41]:
np.maximum(arr2, arr3) # arr2 va arr3 larning elementlarin taqqoslab, kattasining elementini qaytaradi

array([ 0.24778223,  0.67408918, -0.4683328 ,  0.58986736,  0.87397543,
        1.27371848,  0.98244466,  0.4212677 ,  2.2625502 ,  1.97253313])

In [42]:
ar1 = np.random.randn(4)
ar2 = np.random.randn(4)

In [43]:
ar1

array([ 1.37125247, -1.35949   , -0.5826098 , -1.59916879])

In [44]:
ar2

array([-0.85647075,  0.56372141,  0.10909081, -1.23477506])

In [45]:
np.maximum(ar1, ar2)

array([ 1.37125247,  0.56372141,  0.10909081, -1.23477506])