<a href="https://colab.research.google.com/github/khusanovich/colab-jupyter_notebook/blob/main/2_1_3_arithmetics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
arr0 = np.arange(6).reshape(2, 3)

In [3]:
arr1 = np.arange(6, 12).reshape(2, 3)

In [4]:
arr0

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
arr1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
arr0 * arr1 # multiply

array([[ 0,  7, 16],
       [27, 40, 55]])

In [7]:
arr0/arr1 #

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [8]:
arr1/arr0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [9]:
arr0 + arr1

array([[ 6,  8, 10],
       [12, 14, 16]])

In [11]:
arr0

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
arr1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
arr0-arr1

array([[-6, -6, -6],
       [-6, -6, -6]])

In [14]:
# kvadratga oshirish (square)
arr0**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [15]:
arr1**2

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [16]:
# kvadrat ildiz (sqrt)
arr0**0.5

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [18]:
arr1**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])