<a href="https://colab.research.google.com/github/khusanovich/Data_science_and_AI/blob/main/2_2_1_repetition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
fuu = pd.Series([3, 4, 5, 4])

In [ ]:
fuu

0    3
1    4
2    5
3    4
dtype: int64

In [ ]:
fuu[0]

3

In [ ]:
koo = pd.Series([12, 23.4, 4, 5.5], index=['a', 'b', 'c', 'd'])

In [ ]:
koo

a    12.0
b    23.4
c     4.0
d     5.5
dtype: float64

In [ ]:
koo['c']

4.0

In [ ]:
koo.values

array([12. , 23.4,  4. ,  5.5])

In [ ]:
fuu.values

array([3, 4, 5, 4])

In [ ]:
koo.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
fuu.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
koo['e'] = 34

In [ ]:
koo

a    12.0
b    23.4
c     4.0
d     5.5
e    34.0
dtype: float64

In [ ]:
fuu[[3, 2, 0]]

3    4
2    5
0    3
dtype: int64

In [ ]:
koo[['a','c','e']]

a    12.0
c     4.0
e    34.0
dtype: float64

In [ ]:
koo[koo<20]

a    12.0
c     4.0
d     5.5
dtype: float64

In [ ]:
koo*3

a     36.0
b     70.2
c     12.0
d     16.5
e    102.0
dtype: float64

In [ ]:
koo**0.5

a    3.464102
b    4.837355
c    2.000000
d    2.345208
e    5.830952
dtype: float64

In [ ]:
koo

a    12.0
b    23.4
c     4.0
d     5.5
e    34.0
dtype: float64

In [ ]:
np.exp(koo)

a    1.627548e+05
b    1.453754e+10
c    5.459815e+01
d    2.446919e+02
e    5.834617e+14
dtype: float64

In [ ]:
'c' in koo

True

In [ ]:
cars_dict = {'Malibu':40000, 'Lacetti':20000, 'Toyota':45000, 'Mazda':52000, 'Honda':38000} # bu lug'at

In [ ]:
cars_dict

{'Honda': 38000,
 'Lacetti': 20000,
 'Malibu': 40000,
 'Mazda': 52000,
 'Toyota': 45000}

In [32]:
salon0 = pd.Series(cars_dict)

In [ ]:
salon0

Malibu     40000
Lacetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [33]:
salon0['Malibu']

40000

In [34]:
models = ['Honda','Mazda','Lacetti','Jaguar','Malibu','Toyota'] # buyerda bitta qo'shimcha model bor

In [36]:
salon1 = pd.Series(cars_dict, index=models)

In [37]:
salon1

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
dtype: float64

In [38]:
salon0.isnull()

Malibu     False
Lacetti    False
Toyota     False
Mazda      False
Honda      False
dtype: bool

In [39]:
salon1.isnull()

Honda      False
Mazda      False
Lacetti    False
Jaguar      True
Malibu     False
Toyota     False
dtype: bool

`Series` obyektining muhim jihatlaridan biri, ikkita `series` obyektini qo'shishda (ayirishda) qiymatlar indeks bo'yicha qo'shiladi.

In [41]:
# 'Honda','Mazda','Lacetti','Jaguar','Malibu','Toyota'
new_prices = pd.Series({"Honda":5000, "Mazda":-3000, "Malibu":4500, "Toyota":5200, 'Lacetti':-1200})

In [42]:
salon1

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
dtype: float64

In [43]:
new_prices

Honda      5000
Mazda     -3000
Malibu     4500
Toyota     5200
Lacetti   -1200
dtype: int64

In [44]:
salon1+new_prices

Honda      43000.0
Jaguar         NaN
Lacetti    18800.0
Malibu     44500.0
Mazda      49000.0
Toyota     50200.0
dtype: float64

`Series` obyektining o'zini ham indekslarini ham nomlash mumkin:

In [45]:
salon1.name='Avtosalon'

In [46]:
salon1

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
Name: Avtosalon, dtype: float64

In [47]:
salon1.index.name = 'Mashina Modellari'

In [48]:
salon1

Mashina Modellari
Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
Name: Avtosalon, dtype: float64

In [49]:
salon1.name

'Avtosalon'

In [50]:
salon1.index

Index(['Honda', 'Mazda', 'Lacetti', 'Jaguar', 'Malibu', 'Toyota'], dtype='object', name='Mashina Modellari')

In [51]:
salon1.values

array([38000., 52000., 20000.,    nan, 40000., 45000.])

In [52]:
salon1.hasnans # NaN qiymat borligini tekshiradi, True = NaN bor

True

In [53]:
salon1

Mashina Modellari
Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
Name: Avtosalon, dtype: float64

In [54]:
salon0.hasnans

False

In [55]:
salon1.dtype # qiymatlarning ma'lumot turi

dtype('float64')

In [56]:
salon1.is_unique # qiymatlar takrorlanmas ekanini aniqlaydi

True

In [57]:
salon1.shape

(6,)

In [58]:
salon1.size

6

In [59]:
salon1[3]

nan

In [60]:
salon1[4]

40000.0

In [61]:
salon1.iloc[4]

40000.0

In [63]:
salon1.iloc[3]

nan

In [67]:
koo.loc['e']

34.0

In [68]:
salon1.iloc[-2]

40000.0

In [69]:
salon1['Malibu']

40000.0

In [70]:
salon1.loc['Malibu']

40000.0

In [73]:
salon1.max()

52000.0

In [72]:
salon1.min()

20000.0

In [74]:
salon1.mean()

39000.0