In [ ]:
import numpy as np

# Neuer Abschnitt

In [ ]:
my_list = list(range(100000))

In [ ]:
data3 = [[2, 4, 3], [4.5, 4, 5], [3.5, 5, 6], [3, 4, 5]]
arr3 = np.array(data3)

In [ ]:
data3

[[2, 4, 3], [4.5, 4, 5], [3.5, 5, 6], [3, 4, 5]]

In [ ]:
arr3

array([[2. , 4. , 3. ],
       [4.5, 4. , 5. ],
       [3.5, 5. , 6. ],
       [3. , 4. , 5. ]])

In [ ]:
arr3.ndim

2

In [ ]:
d01 = [3, 4, 5, 6]
a01 = np.array(d01)

In [ ]:
d01

[3, 4, 5, 6]

In [ ]:
a01

array([3, 4, 5, 6])

In [ ]:
a01.ndim

1

In [ ]:
d02 = [[3, 4, 5], [3, 4, 5]]
a02 = np.array(d02)

In [ ]:
d02

[[3, 4, 5], [3, 4, 5]]

In [ ]:
a02

array([[3, 4, 5],
       [3, 4, 5]])

In [ ]:
a02.ndim

2

In [ ]:
d03 = [[[3, 4, 5, 6], [3, 3.4, 4.5, 5], [1, 1.5, 2.5, 3]]]
a03 = np.array(d03)

In [ ]:
a03.ndim

3

In [ ]:
a03.shape

(1, 3, 4)

In [ ]:
a03

array([[[3. , 4. , 5. , 6. ],
        [3. , 3.4, 4.5, 5. ],
        [1. , 1.5, 2.5, 3. ]]])

In [ ]:
a03.size

12

In [ ]:
arr4 = np.zeros(shape =(2,4))
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr5 = np.ones((2,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr6 = np.arange(2, 20, 3)
arr6

array([ 2,  5,  8, 11, 14, 17])

In [ ]:
arr7 = np.arange(20)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
data1 = []
arr1 = np.array(data1)

NameError: ignored

In [ ]:
import numpy as np


In [ ]:
data1 = [3, 4]
arr1 = np.array(data1)

In [ ]:
arr1

array([3, 4])

In [ ]:
data1

[3, 4]

In [ ]:
data2 = [[2, 4, 5]]
arr2 = np.array(data2)

In [ ]:
arr2.ndim

2

In [ ]:
arr2.ndim

1

In [ ]:
arr1.ndim

1

In [ ]:
arr8 = np.random.rand(2, 4)

In [ ]:
arr8

array([[0.93595239, 0.80076207, 0.2140471 , 0.70041745],
       [0.67284214, 0.75752159, 0.6773154 , 0.60428252]])

In [ ]:
arr9 = np.random.randint(5, size=(2,4))
arr9

array([[4, 3, 2, 4],
       [2, 3, 3, 0]])

In [ ]:
arr9.ndim

2

In [ ]:
arr10 = np.random.randint(10, size=(3, 4))
arr10

array([[3, 1, 4, 2],
       [0, 1, 4, 6],
       [8, 6, 7, 8]])

In [ ]:
arr11 = np.random.randint(5, size=(4, 4))
arr11

array([[1, 1, 3, 4],
       [1, 0, 1, 0],
       [4, 4, 4, 2],
       [2, 1, 4, 0]])

In [ ]:
arr12 = np.random.randn(4, 4)
arr12

array([[ 0.19593837, -0.859979  ,  0.43607071,  1.92477456],
       [ 0.50714072,  0.57521124, -1.35052261,  0.22952147],
       [-1.74123165,  1.29193922, -0.52009365, -0.81217233],
       [ 0.52008397,  0.96296139, -1.09325372,  1.99198837]])

In [ ]:
d0 = []
ar0 = np.array(d0)

In [ ]:
ar0

array([], dtype=float64)

In [ ]:
arr00 = np.arange(1,10,4)
arr00

array([1, 5, 9])

In [ ]:
arr00.shape

(3,)

In [ ]:
arr00.size

3

In [ ]:
arr01 = np.zeros((3, 4))
arr01

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr02 = np.ones((4, 4))
arr02

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr03 = np.random.randn(1)
arr03

array([-0.88888122])