<a href="https://colab.research.google.com/github/khusanovich/colab-jupyter_notebook/blob/main/array_yaratish_kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
ls



NameError: ignored

In [ ]:
!ls

npynb  sample_data


In [ ]:
cd ./npynb/

/content/npynb


In [ ]:
ls

'vazifa(2_1_1)_arrays.ipynb'


In [ ]:
cd ./vazifa(2_1_1)_arrays.ipynb

[Errno 20] Not a directory: './vazifa(2_1_1)_arrays.ipynb'
/content/npynb


In [ ]:
pwd

'/content/npynb'

In [ ]:
import pandas as pd

dateien = pd.read_csv('./npynb/vazifa(2_1_1)_arrays.ipynb')

FileNotFoundError: ignored

In [ ]:
np.__version__


'1.19.5'

In [ ]:
def one_dim(n):
    
    arr = np.arange(0, n)
    # print(arr)
    return arr
one_dim(40)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
def two_dim(r, c):
    """ r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv  
    """
    arr2 = np.random.randint(10, size= (r, c))
    
    return arr2
two_dim(3, 3)


array([[5, 4, 5],
       [3, 6, 5],
       [5, 8, 0]])

In [ ]:
arr2 = np.random.randint(5, size=(3,4))

In [ ]:
arr2

array([[1, 4, 4, 2],
       [1, 4, 3, 0],
       [1, 3, 1, 1]])

In [ ]:
arr2.ndim

2

In [ ]:
import numpy as np

In [ ]:
data0 = np.random.randint(9, size=(3,3))

In [ ]:
data0

array([[0, 0, 0],
       [2, 2, 6],
       [3, 1, 2]])

In [ ]:
data0.ndim

2

In [ ]:
data0.shape

(3, 3)

In [ ]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
d.shape

(9,)

In [ ]:
def nd_array():
    """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """
    data = np.arange(0, 9, 1)
    return data
nd_array()
    #raise NotImplementedError()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
data = np.arange(0,9)

In [2]:
import numpy as np

In [3]:
data = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
arr = np.array(data)

In [4]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr = np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
def nd_array()
    arr = np.arange(9)
    arr.reshape(3,3)
    return arr


SyntaxError: ignored

In [174]:
def nd_array():
    """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """
    arr = np.arange(9)
    return arr.reshape(3,3)
nd_array()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arr.ndim

2

In [175]:
"""Funksiyani tekshirish"""
arr = nd_array() # massiv
assert arr.size == 9  # elementlar soni
assert type(arr) == np.ndarray # #numpy array 

In [ ]:
def sliced_array_2d():
    """Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasi """
    # YOUR CODE HERE
    raise NotImplementedError()
    

In [33]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
sl_arr = arr[2, :2]

In [35]:
sl_arr

array([6, 7])

In [133]:
def sliced_array_2d():
    """Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasi """
    sl_arr = arr[2, :2]
    return sl_arr
sliced_array_2d()
    #raise NotImplementedError()

array([6, 7])

In [39]:
"""Funksiyani tekshirish"""
sl_arr_2d = sliced_array_2d() # kesib olingan massiv
assert sl_arr_2d.size == 2  # elementlar soni
assert type(sl_arr_2d) == np.ndarray # #numpy array 

In [110]:
arr3d = np.arange(27)
arr3d.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
arr3d.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [59]:
arr3d.ndim

1

In [63]:
arr3d[1]

1

In [64]:
arr3 = np.array([[[0,1,2],
                 [3,4,5],
                 [6,7,8]],
                
                [[9,10,11],
                 [12,13,14],
                 [15,16,17]],
                
                [[18,19,20],
                 [21,22,23],
                 [24,25,26]]])
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [105]:
arr3[1]


array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [108]:
arr3[1][1, :2]


array([12, 13])

In [109]:
arr3[1][1:3, 0:2]

array([[12, 13],
       [15, 16]])

In [149]:
def sliced_array_3d():
    """3-o'lchamli massivni yuqoridagi listdan yaratish, hamda 12, 13, 15, va 16 elementlarini kesib olish funksiyasi"""
    arr3 = np.array([[[0,1,2],
                 [3,4,5],
                 [6,7,8]],
                
                [[9,10,11],
                 [12,13,14],
                 [15,16,17]],
                
                [[18,19,20],
                 [21,22,23],
                 [24,25,26]]])
    sl_arr = arr3[1][1:3, 0:2]
    return sl_arr
sliced_array_3d
   


    #raise NotImplementedError()

<function __main__.sliced_array_3d>

In [150]:
"""Funksiyani tekshirish"""
sl_arr_3d = sliced_array_3d() # kesib olingan massiv
assert sl_arr_3d.size == 4  # elementlar soni
assert type(sl_arr_3d) == np.ndarray # #numpy array

In [142]:
arr3d = np.arange(27)
arr3d.reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [147]:
arr3 = np.array([[[0,1,2],
                 [3,4,5],
                 [6,7,8]],
                
                [[9,10,11],
                 [12,13,14],
                 [15,16,17]],
                
                [[18,19,20],
                 [21,22,23],
                 [24,25,26]]])
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [146]:
arr3[1][1:3, 0:2]

array([[12, 13],
       [15, 16]])

In [151]:
names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])

In [152]:
names

array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U7')

In [154]:
data = np.array([[5, 6, 1, 1],
   [9, 1, 1, 1],
   [7, 7, 4, 2],
   [1, 5, 1, 9],
   [9, 9, 4, 5],
   [7, 5, 9, 6],
   [5, 3, 7, 4]])

In [155]:
data

array([[5, 6, 1, 1],
       [9, 1, 1, 1],
       [7, 7, 4, 2],
       [1, 5, 1, 9],
       [9, 9, 4, 5],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])

In [170]:
mask = (names == 'Javohir') | (names == 'Elyor')
mask

array([False, False,  True,  True, False,  True,  True])

In [169]:
print(names)
print(data)

['Hasan' 'Husan' 'Javohir' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[5 6 1 1]
 [9 1 1 1]
 [7 7 4 2]
 [1 5 1 9]
 [9 9 4 5]
 [7 5 9 6]
 [5 3 7 4]]


In [171]:
data[mask]

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])

In [172]:
def boolean_slicing():
    """Boolean indekslash yordamida ma'lumotlarni kesib olish """
    names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
    data = np.array([[5, 6, 1, 1],
   [9, 1, 1, 1],
   [7, 7, 4, 2],
   [1, 5, 1, 9],
   [9, 9, 4, 5],
   [7, 5, 9, 6],
   [5, 3, 7, 4]])
    mask = (names == 'Javohir') | (names == 'Elyor')
    return data[mask]
    
    #raise NotImplementedError()

In [173]:
"""Funksiyani tekshirish"""
bool_idx = boolean_slicing() # kesib olingan massiv
assert bool_idx.size == 16  # elementlar soni
assert type(bool_idx) == np.ndarray # #numpy array 