<a href="https://colab.research.google.com/github/khusanovich/colab-jupyter_notebook/blob/main/array_oqlarini_almashtirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
A = np.arange(6)

In [4]:
A

array([0, 1, 2, 3, 4, 5])

In [5]:
A.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

Transpose

In [6]:
A.T # A massivning Trasnpose ko'rinishi beradi


array([0, 1, 2, 3, 4, 5])

In [7]:
A = np.arange(6).reshape(3,2)

In [8]:
A.T # A massivning Trasnpose ko'rinishi beradi

array([[0, 2, 4],
       [1, 3, 5]])

swaping axes
# Neuer Abschnitt

In [9]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
A.swapaxes(1, 0) # A massivning Transpose ko'rinishi beradi

array([[0, 2, 4],
       [1, 3, 5]])

Tranposening ishlatilinishiga bir misol AA∧T

In [13]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [12]:
np.dot(A, A.T) # AA^T hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])