<a href="https://colab.research.google.com/github/khusanovich/colab-jupyter_notebook/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [4]:
x 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
y = np.array([[4, 4, 4], [5, 5, 5]])

In [6]:
y

array([[4, 4, 4],
       [5, 5, 5]])

In [7]:
x +y 

array([[ 5.,  6.,  7.],
       [ 9., 10., 11.]])

In [8]:
x*3

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [9]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
y = np.array([[2,4], [3, 1],[3,7]])
y

array([[2, 4],
       [3, 1],
       [3, 7]])

In [11]:
x.dot(y)

array([[17., 27.],
       [41., 63.]])

In [12]:
y.dot(x)

array([[18., 24., 30.],
       [ 7., 11., 15.],
       [31., 41., 51.]])

In [13]:
np.dot(x,y)

array([[17., 27.],
       [41., 63.]])

In [14]:
np.dot(y,x)

array([[18., 24., 30.],
       [ 7., 11., 15.],
       [31., 41., 51.]])